name: CMake Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]
        - os: windows-latest
          build_type: Release
          package_manager: msys2
        - os: windows-latest
          build_type: Release
          package_manager: osgeo4w


    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: true

    # Linux dependencies
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git \
          libgsl-dev libgdal-dev libhdf5-dev libtiff-dev libgeotiff-dev

    # macOS dependencies
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake gsl gdal hdf5 libtiff libgeotiff

    # Windows dependencies using MSYS2
    - name: Install MSYS2 and dependencies (Windows)
      if: ${{ runner.os == 'Windows' && package_manager == 'msys2' }}
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gsl
          mingw-w64-x86_64-gdal
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-libtiff
          mingw-w64-x86_64-libgeotiff
          make
        shell: msys2 {0}
    
    - name: Setup OSGeo4W environment
      id: setup-osgeo4w
      if: ${{ runner.os == 'Windows' && package_manager == 'osgeo4w' }}
      uses: echoix/setup-OSGeo4W@v0.2.0
      with:
        packages: >-
          gdal-devel
          geos-devel
          hdf5-devel
          libgeotiff-devel
          libtiff-devel
          gsl-devel
    
    - name: Configure Build CMake MSYS
      if: ${{ runner.os == 'Windows' && package_manager == 'msys2' }}
      run: |
        cmake -B build -S . -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build build --config ${{ matrix.build_type }}
      shell: msys2 {0}

    - name: Configure Build CMake OSGeo4W
      if: ${{ runner.os == 'Windows' && package_manager == 'osgeo4w' }}
      run: |
        cmake -B build -S . -G"Visual Studio 17 Win64" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PREFIX_PATH=C:\OSGeo4W
        cmake --build build --config ${{ matrix.build_type }}
      shell: cmd {0}

    - name: CMake Build
      if: runner.os != 'Windows'
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build build --config ${{ matrix.build_type }}
      shell: bash
